name: build-prod
on: 
 - workflow_dispatch
jobs:
  build_docker-prod:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to docker repo
        uses: docker/login-action@v2
        with:
          registry: docker.infra.phoenixlan.no
          username: ${{ secrets.REGISTRY_USERNAME}}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          build-args: |
            BASE_URL=https://api.phoenixlan.no
            HOST=https://delta.phoenixlan.no
            REACT_APP_MAIN_SITE=https://phoenixlan.no
            REACT_APP_OAUTH_CLIENT_ID=phoenix-delta
            STRIPE_PK=${{ secrets.STRIPE_PK_PROD }}
            REACT_APP_SENTRY_DSN=${{ secrets.SENTRY_DSN_PROD }}
          file: "docker/production/Dockerfile"
          context: .
          push: true
          tags: |
            docker.infra.phoenixlan.no/web/${{ github.event.repository.name }}-prod:latest
            docker.infra.phoenixlan.no/web/${{ github.event.repository.name }}-prod:${{ github.sha }}